[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/bin/main.rs"
name = "zero2prod"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.24.1", features = ["full"] }
config = "0.13.3"
dotenv = "0.15.0"
uuid = { version = "1.2.2", features = ["serde", "v4"] }
chrono = {version = "0.4.23", default-features = false, features = ["clock"]}
regex = "1.7.1"

[dependencies.sqlx]
version = "0.6.2"
default-features = false
features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate"]

[dev-dependencies]
reqwest = "0.11.13"
