version: 3

dotenv: [.env]

includes:
  run:
    taskfile: taskfiles/Run.yml
    aliases: [r]
  test:
    taskfile: taskfiles/Test.yml
    aliases: [t]
  database:
    taskfile: taskfiles/Database.yml
    aliases: [db]
